/* ==========================================================================
   Dorum Lifestyle · public brokerage site (generated by the Llave OS CMS)
   Shared layer for dorum/index.html, listing.html, lifestyle.html.
   Plain script. Depends on window.DORUM (../assets/data.js) loaded before.
   Exposes ONE global: window.SITE
   ========================================================================== */
(function () {
  'use strict';
  var D = window.DORUM;
  var S = {};

  /* ------------------------------------------------------------------ icons */
  // Lucide-style outlines, 24×24, stroke currentColor 1.75.
  var P = {
    search: '<circle cx="11" cy="11" r="8"/><path d="m21 21-4.35-4.35"/>',
    pin: '<path d="M20 10c0 6-8 12-8 12s-8-6-8-12a8 8 0 0 1 16 0Z"/><circle cx="12" cy="10" r="3"/>',
    bed: '<path d="M2 4v16"/><path d="M2 8h18a2 2 0 0 1 2 2v10"/><path d="M2 17h20"/><path d="M6 8v9"/>',
    bath: '<path d="M9 6 6.5 3.5a1.5 1.5 0 0 0-1-.5C4.683 3 4 3.683 4 4.5V17a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2v-5"/><path d="M10 5 8 7"/><path d="M2 12h20"/><path d="M7 19v2"/><path d="M17 19v2"/>',
    car: '<path d="M19 17h2c.6 0 1-.4 1-1v-3c0-.9-.7-1.7-1.5-1.9C18.7 10.6 16 10 16 10s-1.3-1.4-2.2-2.3c-.5-.4-1.1-.7-1.8-.7H5c-.6 0-1.1.4-1.4.9l-1.4 2.9A3.7 3.7 0 0 0 2 12v4c0 .6.4 1 1 1h2"/><circle cx="7" cy="17" r="2"/><path d="M9 17h6"/><circle cx="17" cy="17" r="2"/>',
    area: '<path d="M8 3H5a2 2 0 0 0-2 2v3"/><path d="M21 8V5a2 2 0 0 0-2-2h-3"/><path d="M3 16v3a2 2 0 0 0 2 2h3"/><path d="M16 21h3a2 2 0 0 0 2-2v-3"/>',
    phone: '<path d="M22 16.92v3a2 2 0 0 1-2.18 2 19.79 19.79 0 0 1-8.63-3.07 19.5 19.5 0 0 1-6-6 19.79 19.79 0 0 1-3.07-8.67A2 2 0 0 1 4.11 2h3a2 2 0 0 1 2 1.72c.127.96.361 1.903.7 2.81a2 2 0 0 1-.45 2.11L8.09 9.91a16 16 0 0 0 6 6l1.27-1.27a2 2 0 0 1 2.11-.45c.907.339 1.85.573 2.81.7A2 2 0 0 1 22 16.92z"/>',
    chat: '<path d="M7.9 20A9 9 0 1 0 4 16.1L2 22Z"/>',
    calendar: '<rect x="3" y="4" width="18" height="18" rx="2"/><path d="M16 2v4"/><path d="M8 2v4"/><path d="M3 10h18"/>',
    share: '<circle cx="18" cy="5" r="3"/><circle cx="6" cy="12" r="3"/><circle cx="18" cy="19" r="3"/><path d="m8.59 13.51 6.83 3.98"/><path d="m15.41 6.51-6.82 3.98"/>',
    sun: '<circle cx="12" cy="12" r="4"/><path d="M12 2v2"/><path d="M12 20v2"/><path d="m4.93 4.93 1.41 1.41"/><path d="m17.66 17.66 1.41 1.41"/><path d="M2 12h2"/><path d="M20 12h2"/><path d="m6.34 17.66-1.41 1.41"/><path d="m19.07 4.93-1.41 1.41"/>',
    moon: '<path d="M12 3a6 6 0 0 0 9 9 9 9 0 1 1-9-9Z"/>',
    menu: '<path d="M4 6h16"/><path d="M4 12h16"/><path d="M4 18h16"/>',
    arrow: '<path d="M5 12h14"/><path d="m12 5 7 7-7 7"/>',
    left: '<path d="m15 18-6-6 6-6"/>',
    right: '<path d="m9 18 6-6-6-6"/>',
    x: '<path d="M18 6 6 18"/><path d="m6 6 12 12"/>',
    leaf: '<path d="M11 20A7 7 0 0 1 9.8 6.1C15.5 5 17 4.48 19 2c1 2 2 4.18 2 8 0 5.5-4.78 10-10 10Z"/><path d="M2 21c0-3 1.85-5.36 5.08-6C9.5 14.52 12 13 13 12"/>',
    key: '<path d="m15.5 7.5 2.3 2.3a1 1 0 0 0 1.4 0l2.1-2.1a1 1 0 0 0 0-1.4L19 4"/><path d="m21 2-9.6 9.6"/><circle cx="7.5" cy="15.5" r="5.5"/>',
    building: '<rect x="4" y="2" width="16" height="20" rx="2"/><path d="M9 22v-4h6v4"/><path d="M8 6h.01"/><path d="M16 6h.01"/><path d="M12 6h.01"/><path d="M12 10h.01"/><path d="M12 14h.01"/><path d="M16 10h.01"/><path d="M16 14h.01"/><path d="M8 10h.01"/><path d="M8 14h.01"/>',
    hammer: '<path d="m15 12-8.373 8.373a1 1 0 1 1-3-3L12 9"/><path d="m18 15 4-4"/><path d="m21.5 11.5-1.914-1.914A2 2 0 0 1 19 8.172V7l-2.26-2.26a6 6 0 0 0-4.202-1.756L9 2.96l.92.82A6.18 6.18 0 0 1 12 8.4V10l2 2h1.172a2 2 0 0 1 1.414.586L18.5 14.5"/>',
    heart: '<path d="M19 14c1.49-1.46 3-3.21 3-5.5A5.5 5.5 0 0 0 16.5 3c-1.76 0-3 .5-4.5 2-1.5-1.5-2.74-2-4.5-2A5.5 5.5 0 0 0 2 8.5c0 2.3 1.5 4.05 3 5.5l7 7Z"/>',
    check: '<path d="M20 6 9 17l-5-5"/>',
    mail: '<rect x="2" y="4" width="20" height="16" rx="2"/><path d="m22 7-8.97 5.7a1.94 1.94 0 0 1-2.06 0L2 7"/>',
    globe: '<circle cx="12" cy="12" r="10"/><path d="M12 2a14.5 14.5 0 0 0 0 20 14.5 14.5 0 0 0 0-20"/><path d="M2 12h20"/>',
    external: '<path d="M15 3h6v6"/><path d="M10 14 21 3"/><path d="M18 13v6a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2h6"/>',
    sparkles: '<path d="M9.937 15.5A2 2 0 0 0 8.5 14.063l-6.135-1.582a.5.5 0 0 1 0-.962L8.5 9.936A2 2 0 0 0 9.937 8.5l1.582-6.135a.5.5 0 0 1 .963 0L14.063 8.5A2 2 0 0 0 15.5 9.937l6.135 1.581a.5.5 0 0 1 0 .964L15.5 14.063a2 2 0 0 0-1.437 1.437l-1.582 6.135a.5.5 0 0 1-.963 0z"/><path d="M20 3v4"/><path d="M22 5h-4"/>',
    home: '<path d="M3 10a2 2 0 0 1 .709-1.528l7-5.999a2 2 0 0 1 2.582 0l7 5.999A2 2 0 0 1 21 10v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2z"/><path d="M9 21v-6a1 1 0 0 1 1-1h4a1 1 0 0 1 1 1v6"/>',
    trend: '<path d="M16 7h6v6"/><path d="m22 7-8.5 8.5-5-5L2 17"/>',
    bag: '<path d="M6 2 3 6v14a2 2 0 0 0 2 2h14a2 2 0 0 0 2-2V6l-3-4Z"/><path d="M3 6h18"/><path d="M16 10a4 4 0 0 1-8 0"/>',
    utensils: '<path d="M3 2v7c0 1.1.9 2 2 2h4a2 2 0 0 0 2-2V2"/><path d="M7 2v20"/><path d="M21 15V2a5 5 0 0 0-5 5v6c0 1.1.9 2 2 2h3Zm0 0v7"/>',
    boat: '<path d="M22 18H2a4 4 0 0 0 4 4h12a4 4 0 0 0 4-4Z"/><path d="M21 14 10 2 3 14h18Z"/><path d="M10 2v16"/>',
    truck: '<path d="M14 18V6a2 2 0 0 0-2-2H4a2 2 0 0 0-2 2v11a1 1 0 0 0 1 1h2"/><path d="M15 18H9"/><path d="M19 18h2a1 1 0 0 0 1-1v-3.65a1 1 0 0 0-.22-.624l-3.48-4.35A1 1 0 0 0 17.52 8H14"/><circle cx="17" cy="18" r="2"/><circle cx="7" cy="18" r="2"/>',
    mountain: '<path d="m8 3 4 8 5-5 5 15H2L8 3z"/>',
    waves: '<path d="M2 6c.6.5 1.2 1 2.5 1C7 7 7 5 9.5 5c2.6 0 2.4 2 5 2 2.5 0 2.5-2 5-2 1.3 0 1.9.5 2.5 1"/><path d="M2 12c.6.5 1.2 1 2.5 1 2.5 0 2.5-2 5-2 2.6 0 2.4 2 5 2 2.5 0 2.5-2 5-2 1.3 0 1.9.5 2.5 1"/><path d="M2 18c.6.5 1.2 1 2.5 1 2.5 0 2.5-2 5-2 2.6 0 2.4 2 5 2 2.5 0 2.5-2 5-2 1.3 0 1.9.5 2.5 1"/>',
    file: '<path d="M15 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V7Z"/><path d="M14 2v4a2 2 0 0 0 2 2h4"/><path d="M10 9H8"/><path d="M16 13H8"/><path d="M16 17H8"/>',
    camera: '<path d="M14.5 4h-5L7 7H4a2 2 0 0 0-2 2v9a2 2 0 0 0 2 2h16a2 2 0 0 0 2-2V9a2 2 0 0 0-2-2h-3l-2.5-3z"/><circle cx="12" cy="13" r="3"/>',
    layers: '<path d="m12.83 2.18a2 2 0 0 0-1.66 0L2.6 6.08a1 1 0 0 0 0 1.83l8.58 3.91a2 2 0 0 0 1.66 0l8.58-3.9a1 1 0 0 0 0-1.83Z"/><path d="m22 12.65-9.17 4.16a2 2 0 0 1-1.66 0L2 12.65"/><path d="m22 17.65-9.17 4.16a2 2 0 0 1-1.66 0L2 17.65"/>',
    copy: '<rect x="8" y="8" width="14" height="14" rx="2"/><path d="M4 16c-1.1 0-2-.9-2-2V4c0-1.1.9-2 2-2h10c1.1 0 2 .9 2 2"/>',
    wallet: '<path d="M19 7V4a1 1 0 0 0-1-1H5a2 2 0 0 0 0 4h15a1 1 0 0 1 1 1v4h-3a2 2 0 0 0 0 4h3a1 1 0 0 0 1-1v-2a1 1 0 0 0-1-1"/><path d="M3 5v14a2 2 0 0 0 2 2h15a1 1 0 0 0 1-1v-4"/>',
    shield: '<path d="M20 13c0 5-3.5 7.5-7.66 8.95a1 1 0 0 1-.67-.01C7.5 20.5 4 18 4 13V6a1 1 0 0 1 1-1c2 0 4.5-1.2 6.24-2.72a1.17 1.17 0 0 1 1.52 0C14.51 3.81 17 5 19 5a1 1 0 0 1 1 1z"/>',
    star: '<path d="M11.525 2.295a.53.53 0 0 1 .95 0l2.31 4.679a2.123 2.123 0 0 0 1.595 1.16l5.166.756a.53.53 0 0 1 .294.904l-3.736 3.638a2.123 2.123 0 0 0-.611 1.878l.882 5.14a.53.53 0 0 1-.771.56l-4.618-2.428a2.122 2.122 0 0 0-1.973 0L6.396 21.01a.53.53 0 0 1-.77-.56l.881-5.139a2.122 2.122 0 0 0-.611-1.879L2.16 9.795a.53.53 0 0 1 .294-.906l5.165-.755a2.122 2.122 0 0 0 1.597-1.16z"/>',
    tree: '<path d="M12 22v-5"/><path d="M8 17h8l-1.6-3H9.6Z"/><path d="M7 14h10l-2-4H9Z"/><path d="M9 10h6l-3-6Z"/>',
    quote: '<path d="M16 3a2 2 0 0 0-2 2v6a2 2 0 0 0 2 2 1 1 0 0 1 1 1v1a2 2 0 0 1-2 2 1 1 0 0 0 0 2 4 4 0 0 0 4-4V5a2 2 0 0 0-2-2z"/><path d="M5 3a2 2 0 0 0-2 2v6a2 2 0 0 0 2 2 1 1 0 0 1 1 1v1a2 2 0 0 1-2 2 1 1 0 0 0 0 2 4 4 0 0 0 4-4V5a2 2 0 0 0-2-2z"/>'
  };
  S.icon = function (name, cls) {
    return '<svg class="ico' + (cls ? ' ' + cls : '') + '" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.75" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">' + (P[name] || P.pin) + '</svg>';
  };
  S.iconFor = { 'ls-house': 'home', 'ls-food': 'utensils', 'ls-act': 'boat', 'ls-trans': 'truck', 'ls-conc': 'key', 'ls-remodel': 'hammer', 'ls-build': 'building',
    'real-estate': 'home', 'lifestyle': 'leaf', 'projects': 'hammer', 'foundation': 'heart', 'boutique': 'bag' };

  /* ------------------------------------------------------------------- i18n */
  // Navigation, hero, section titles and CTAs are bilingual. Body copy stays in Spanish (the CMS keeps a second column for EN).
  S.T = {
    'nav.inmuebles': ['Inmuebles', 'Properties'], 'nav.colecciones': ['Colecciones', 'Collections'], 'nav.lifestyle': ['Lifestyle', 'Lifestyle'],
    'nav.nosotros': ['Nosotros', 'About'], 'nav.contacto': ['Contacto', 'Contact'], 'nav.whatsapp': ['WhatsApp', 'WhatsApp'],
    'nav.theme': ['Cambiar tema', 'Toggle theme'], 'nav.menu': ['Menú', 'Menu'],
    'hero.eyebrow': ['Curated by nature · Guatapé · Medellín · Oriente · Cartagena', 'Curated by nature · Guatapé · Medellín · Oriente · Cartagena'],
    'hero.title': ['Hogares inmersos en la <em>naturaleza</em>, listos para la vida moderna.', 'Homes immersed in <em>nature</em>, ready for modern life.'],
    'hero.cta1': ['Ver inmuebles', 'Browse properties'], 'hero.cta2': ['Hablar por WhatsApp', 'Chat on WhatsApp'],
    'search.title': ['¿Qué estás buscando?', 'What are you looking for?'],
    'search.op': ['Operación', 'Looking to'], 'search.type': ['Tipo', 'Type'], 'search.zone': ['Zona', 'Area'], 'search.budget': ['Presupuesto', 'Budget'],
    'search.go': ['Buscar', 'Search'], 'search.any': ['Cualquiera', 'Any'], 'search.buy': ['Comprar', 'Buy'], 'search.rent': ['Arrendar', 'Rent'], 'search.stay': ['Vacacional', 'Vacation stay'],
    'gal.eyebrow': ['Galería de inmuebles', 'Property gallery'], 'gal.title': ['Seleccionados con el sello <em>Dorum</em>', 'Selected with the <em>Dorum</em> seal'],
    'gal.lead': ['Cada propiedad pasa por nuestro filtro: paisaje, bienestar, construcción honesta y potencial como activo productivo.', 'Every property passes our filter: landscape, well-being, honest construction and potential as a productive asset.'],
    'gal.buy': ['Compra', 'Buy'], 'gal.rent': ['Arriendo', 'Rent'], 'gal.stay': ['Vacacional', 'Vacation'], 'gal.all': ['Todas las zonas', 'All areas'],
    'gal.empty': ['No hay inmuebles con esos filtros. Cuéntanos qué buscas y lo encontramos.', 'Nothing matches those filters yet. Tell us what you need and we will find it.'],
    'gal.clear': ['Limpiar filtros', 'Clear filters'],
    'col.eyebrow': ['Colecciones', 'Collections'], 'col.title': ['Tres maneras de vivir <em>Dorum</em>', 'Three ways to live <em>Dorum</em>'],
    'col.lake': ['Vida en el embalse', 'Life on the reservoir'], 'col.lake.d': ['Guatapé, Tierra Prometida y las veredas del agua.', 'Guatapé, Tierra Prometida and the lakeside veredas.'],
    'col.finca': ['Fincas y casas campestres', 'Fincas & country homes'], 'col.finca.d': ['Llanogrande, El Retiro y Guarne, a minutos del aeropuerto.', 'Llanogrande, El Retiro and Guarne, minutes from the airport.'],
    'col.med': ['Medellín curado', 'Curated Medellín'], 'col.med.d': ['El Poblado, Laureles y Envigado con criterio boutique.', 'El Poblado, Laureles and Envigado, with boutique criteria.'],
    'col.see': ['Ver todo', 'See all'],
    'ls.eyebrow': ['Lifestyle & Experiences', 'Lifestyle & Experiences'], 'ls.title': ['Convierte tu compra en un <em>activo productivo</em>', 'Turn your purchase into a <em>productive asset</em>'],
    'ls.lead': ['Administramos tu casa de descanso o apartamento: reservas, limpieza, experiencias y liquidación mensual. Tú recibes el extracto; nosotros hacemos el resto.', 'We manage your holiday home or apartment: bookings, cleaning, experiences and a monthly statement. You get the report; we do the rest.'],
    'ls.cta': ['Conocer Lifestyle & Experiences', 'Explore Lifestyle & Experiences'], 'ls.soon': ['Próximamente', 'Coming soon'], 'ls.pilot': ['Piloto', 'Pilot'],
    'div.eyebrow': ['Dorum Group', 'Dorum Group'], 'div.title': ['Cinco divisiones, una misma <em>misión</em>', 'Five divisions, one <em>mission</em>'],
    'team.eyebrow': ['Nosotros', 'About us'], 'team.title': ['Un equipo que vive donde <em>vende</em>', 'A team that lives where it <em>sells</em>'],
    'team.owner': ['Fundadora', 'Founder'], 'team.markets': ['Mercados', 'Markets'], 'team.offices': ['Oficinas', 'Offices'],
    'test.eyebrow': ['Testimonios', 'Testimonials'], 'test.title': ['Lo que dicen quienes ya viven <em>Dorum</em>', 'From people already living <em>Dorum</em>'],
    'ct.eyebrow': ['Contacto', 'Contact'], 'ct.title': ['Cuéntanos qué <em>buscas</em>', 'Tell us what you are <em>looking for</em>'],
    'ct.lead': ['Un asesor te escribe hoy. Sin formularios largos: nombre, WhatsApp y lo que tienes en mente.', 'An advisor writes to you today. No long forms: name, WhatsApp and what you have in mind.'],
    'ct.name': ['Nombre', 'Name'], 'ct.wa': ['WhatsApp', 'WhatsApp'], 'ct.interest': ['Interés', 'Interest'], 'ct.send': ['Enviar', 'Send'],
    'ct.i1': ['Comprar', 'Buy'], 'ct.i2': ['Arrendar', 'Rent'], 'ct.i3': ['Vender o arrendar mi propiedad', 'Sell or rent out my property'], 'ct.i4': ['Rentar mi casa con Lifestyle', 'Rent my home with Lifestyle'], 'ct.i5': ['Proyecto o construcción', 'Project or construction'],
    'ct.note': ['Tu mensaje entra directo al CRM de Llave: el asesor lo ve en su Captación con tu fuente “Sitio web”.', 'Your message goes straight into the Llave CRM: the advisor sees it in their pipeline with source “Website”.'],
    'toast.ok': ['Recibido — un asesor te escribe hoy', 'Received — an advisor writes to you today'],
    'toast.ok.body': ['Quedó registrado en el CRM de Llave como lead de Sitio web.', 'Logged in the Llave CRM as a Website lead.'],
    'foot.tag': ['Agencia boutique de hogares inmersos en la naturaleza. Medellín · Guatapé · Oriente · Cartagena · México · Dubái.', 'Boutique agency for homes immersed in nature. Medellín · Guatapé · Oriente · Cartagena · México · Dubai.'],
    'foot.props': ['Inmuebles', 'Properties'], 'foot.buy': ['Compra', 'Buy'], 'foot.rent': ['Arriendo', 'Rent'], 'foot.stay': ['Vacacional', 'Vacation'],
    'foot.group': ['Grupo', 'Group'], 'foot.about': ['Nosotros', 'About'], 'foot.contact': ['Contacto', 'Contact'],
    'foot.legal': ['Datos de demostración. Equipo de ejemplo con nombres ficticios, excepto la fundadora. Fotos de muestra.', 'Demo data. Sample team with fictional names, except the founder. Sample photos.'],
    'foot.llave': ['Sitio generado con Llave OS', 'Site generated with Llave OS'], 'foot.cms': ['editar en el CMS', 'edit in the CMS'],
    // listing page
    'l.back': ['Volver a inmuebles', 'Back to properties'], 'l.photos': ['Ver todas las fotos', 'See all photos'],
    'l.desc': ['Descripción', 'Description'], 'l.amen': ['Lo que hace especial este lugar', 'What makes this place special'],
    'l.map': ['Ubicación', 'Location'], 'l.map.note': ['Mapa ilustrativo. La ubicación exacta se comparte con la visita agendada.', 'Illustrative map. The exact location is shared once a visit is booked.'],
    'l.agent': ['Tu asesor', 'Your advisor'], 'l.wa': ['WhatsApp', 'WhatsApp'], 'l.call': ['Llamar', 'Call'],
    'l.visit': ['Agendar visita', 'Book a visit'], 'l.visit.lead': ['Elige día y hora. Confirmamos por WhatsApp.', 'Pick a day and time. We confirm on WhatsApp.'],
    'l.date': ['Fecha', 'Date'], 'l.time': ['Hora', 'Time'], 'l.visit.cta': ['Agendar', 'Book'],
    'l.visit.toast': ['Visita solicitada', 'Visit requested'], 'l.visit.body': ['Quedó en la agenda de tu asesor; te confirma por WhatsApp.', 'It is on your advisor’s calendar; they confirm on WhatsApp.'],
    'l.mort': ['Simular crédito', 'Mortgage estimate'], 'l.mort.lead': ['Estimación orientativa en pesos. La tasa es un supuesto de demo, no una oferta de crédito.', 'Indicative estimate in pesos. The rate is a demo assumption, not a loan offer.'],
    'l.down': ['Cuota inicial', 'Down payment'], 'l.term': ['Plazo', 'Term'], 'l.rate': ['Tasa E.A.', 'Annual rate'], 'l.monthly': ['Cuota mensual estimada', 'Estimated monthly payment'], 'l.financed': ['Monto financiado', 'Amount financed'],
    'l.years': ['años', 'years'],
    'l.yield': ['Rentabilidad estimada', 'Estimated returns'], 'l.yield.lead': ['Así se vería el extracto mensual del propietario bajo administración Dorum Lifestyle & Experiences.', 'This is how the owner’s monthly statement would look under Dorum Lifestyle & Experiences management.'],
    'l.occ': ['Ocupación', 'Occupancy'], 'l.gross': ['Ingreso bruto mensual', 'Gross monthly income'], 'l.fee': ['Administración integral', 'Full management'], 'l.net': ['Liquidación al propietario', 'Owner payout'],
    'l.yield.note': ['Estimación de demo. No incluye IVA sobre el fee ni gastos de limpieza y experiencias, que se trasladan al huésped.', 'Demo estimate. Excludes VAT on the fee and cleaning or experience costs, which are passed to the guest.'],
    'l.invest': ['¿Comprar para rentar?', 'Buying to rent out?'], 'l.invest.body': ['Esta propiedad puede entrar al programa Lifestyle & Experiences: reservas, limpieza y liquidación mensual administradas por Dorum.', 'This property can join the Lifestyle & Experiences programme: bookings, cleaning and monthly payout managed by Dorum.'],
    'l.similar': ['Inmuebles similares', 'Similar properties'], 'l.share': ['Compartir', 'Share'], 'l.copy': ['Copiar enlace', 'Copy link'], 'l.copied': ['Enlace copiado', 'Link copied'],
    'l.synd': ['También publicado en', 'Also listed on'], 'l.synd.none': ['Publicación exclusiva en dorumgroup.com', 'Listed exclusively on dorumgroup.com'],
    'l.spec.area': ['Área construida', 'Built area'], 'l.spec.lote': ['Lote', 'Lot'], 'l.spec.hab': ['Habitaciones', 'Bedrooms'], 'l.spec.ban': ['Baños', 'Bathrooms'], 'l.spec.parq': ['Parqueaderos', 'Parking'],
    'l.spec.estrato': ['Estrato', 'Estrato'], 'l.spec.admin': ['Administración', 'HOA fee'], 'l.spec.ano': ['Año', 'Year built'], 'l.perm2': ['por m²', 'per m²'], 'l.notfound': ['No encontramos ese inmueble.', 'We could not find that property.'],
    'l.mes': ['/ mes', '/ month'],
    // lifestyle page
    'lf.eyebrow': ['Dorum Lifestyle & Experiences', 'Dorum Lifestyle & Experiences'],
    'lf.title': ['Tu casa de descanso, trabajando <em>por ti</em>', 'Your holiday home, working <em>for you</em>'],
    'lf.lead': ['Administración integral de rentas vacacionales y de vivienda en el embalse, el Oriente y Medellín. Convertimos compras en activos productivos, sin que tengas que estar allí.', 'Full management of vacation and residential rentals across the reservoir, the Oriente and Medellín. We turn purchases into productive assets without you having to be there.'],
    'lf.cta1': ['Quiero rentar mi propiedad', 'I want to rent out my property'], 'lf.cta2': ['Ver propiedades del programa', 'See programme properties'],
    'lf.how': ['Cómo funciona', 'How it works'], 'lf.how.title': ['Cuatro pasos, un <em>extracto</em> al mes', 'Four steps, one <em>statement</em> a month'],
    'lf.stmt': ['Extracto del propietario', 'Owner statement'], 'lf.stmt.title': ['Así se ve tu <em>liquidación</em> mensual', 'This is what your monthly <em>payout</em> looks like'],
    'lf.services': ['Servicios', 'Services'], 'lf.services.title': ['Todo lo que rodea a la <em>casa</em>', 'Everything around the <em>house</em>'],
    'lf.exp': ['Experiencias en Guatapé', 'Experiences in Guatapé'], 'lf.exp.title': ['El embalse, <em>curado</em>', 'The reservoir, <em>curated</em>'],
    'lf.proj': ['Dorum Projects', 'Dorum Projects'], 'lf.proj.title': ['Remodelar o construir <em>desde cero</em>', 'Remodel or build <em>from scratch</em>'],
    'lf.quote': ['Cotizar', 'Get a quote'], 'lf.quote.toast': ['Solicitud de cotización enviada', 'Quote request sent'], 'lf.quote.body': ['Dorum Projects te contacta esta semana. Registrada como orden en Llave.', 'Dorum Projects contacts you this week. Logged as an order in Llave.'],
    'lf.owner.toast': ['Recibido — Lifestyle te escribe hoy', 'Received — Lifestyle writes to you today'], 'lf.owner.body': ['Entró al CRM de Llave como lead de propietario (Captación).', 'Logged in the Llave CRM as a landlord lead.'],
    'lf.form.title': ['Cuéntanos de tu propiedad', 'Tell us about your property'], 'lf.form.prop': ['¿Qué propiedad tienes?', 'What property do you own?'], 'lf.form.zone': ['Zona', 'Area'], 'lf.form.send': ['Quiero una propuesta', 'Send me a proposal'],
    'lf.demo': ['Demo', 'Demo'], 'lf.book': ['Reservar', 'Book'], 'lf.book.toast': ['Solicitud enviada', 'Request sent'], 'lf.book.body': ['Concierge Lifestyle te confirma por WhatsApp.', 'Lifestyle concierge confirms on WhatsApp.']
  };
  // Language is owned by the shared toggle (../assets/i18n.js → window.I18N, localStorage 'llave-lang').
  // S.lang stays as a read-only view of it so the page scripts keep working unchanged.
  Object.defineProperty(S, 'lang', { get: function () { return (window.I18N && window.I18N.lang) || 'es'; } });
  S.t = function (key) { var v = S.T[key]; return v ? v[S.lang === 'en' ? 1 : 0] : key; };
  S.applyLang = function (root) {
    root = root || document;
    document.documentElement.lang = S.lang;
    root.querySelectorAll('[data-i18n]').forEach(function (el) { el.innerHTML = S.t(el.getAttribute('data-i18n')); });
    root.querySelectorAll('[data-i18n-ph]').forEach(function (el) { el.placeholder = S.t(el.getAttribute('data-i18n-ph')); });
    root.querySelectorAll('[data-i18n-label]').forEach(function (el) { el.setAttribute('aria-label', S.t(el.getAttribute('data-i18n-label'))); });
    document.dispatchEvent(new CustomEvent('dorum:lang', { detail: S.lang }));
  };
  S.setLang = function (lang) { if (window.I18N) window.I18N.set(lang); else S.applyLang(); };
  if (window.I18N) window.I18N.onChange(function () { S.applyLang(); });
  // Listing copy helpers (titleEn / descEn live in data.js)
  S.title = function (l) { return D.tx ? D.tx(l, 'title') : l.title; };
  S.desc = function (l) { return D.tx ? D.tx(l, 'description', 'descEn') : l.description; };
  S.ls = function (svc) { return { name: S.lang === 'en' ? svc.name : svc.nameEs, desc: S.lang === 'en' && svc.descEn ? svc.descEn : svc.desc }; };

  /* ------------------------------------------------------------- data views */
  S.WA = 'https://wa.me/573100000000'; // demo placeholder number
  S.wa = function (text, phone) {
    var p = (phone || '').replace(/\D/g, '');
    return 'https://wa.me/' + (p || '573100000000') + (text ? '?text=' + encodeURIComponent(text) : '');
  };
  S.ZONES = [
    { id: 'guatape', label: 'Guatapé' }, { id: 'oriente', label: 'Oriente Antioqueño' }, { id: 'medellin', label: 'Medellín' },
    { id: 'cartagena', label: 'Cartagena' }, { id: 'intl', label: 'Internacional' }
  ];
  S.zoneOf = function (l) {
    if (l.international || l.currency === 'USD') return 'intl';
    var c = l.city;
    if (/Guatap|Peñol/.test(c)) return 'guatape';
    if (/Rionegro|Retiro|Guarne|Ceja|Marinilla|Carmen/.test(c)) return 'oriente';
    if (/Medell|Envigado|Sabaneta|Itag|Bello/.test(c)) return 'medellin';
    if (/Cartagena/.test(c)) return 'cartagena';
    return 'oriente';
  };
  S.zoneLabel = function (id) { var z = D.byId(S.ZONES, id); return z ? z.label : id; };
  S.modeOf = function (l) { return l.operacion === 'venta' ? 'buy' : (l.rentalType === 'vacacional' ? 'stay' : 'rent'); };
  S.priceCOP = function (l) { return l.currency === 'USD' ? l.price * 4000 : l.price; }; // rough demo FX for filters only
  S.publicListings = function () {
    return D.listings.filter(function (l) { return l.status === 'activo' || l.status === 'bajo oferta' || l.status === 'arrendado'; });
  };
  S.featured = function () { return S.publicListings().filter(function (l) { return l.featured; }); };

  S.specs = function (l) {
    var out = [], en = S.lang === 'en';
    if (l.area) out.push(D.fmtM2(l.area));
    if (l.habitaciones) out.push(l.habitaciones + (en ? ' bd' : ' hab'));
    if (l.banos) out.push(l.banos + (en ? (l.banos === 1 ? ' bath' : ' baths') : (l.banos === 1 ? ' baño' : ' baños')));
    if (l.parqueaderos) out.push(l.parqueaderos + (en ? ' parking' : ' parq'));
    if (l.type === 'lote' && l.areaLote) out = [D.fmtM2(l.areaLote) + (en ? ' lot' : ' lote')];
    return out;
  };
  S.listingCard = function (l) {
    var badge = '<span class="badge badge-status" data-status="' + l.status + '">' + D.statusLabel(l.status) + '</span>';
    var en = S.lang === 'en';
    var intl = l.currency === 'USD' ? '<span class="pill pill-accent dz-pill-right">' + (en ? 'International' : 'Internacional') + '</span>' : '';
    var unit = l.operacion === 'venta' ? (en ? 'for sale' : 'venta') : (l.priceUnit === 'noche' ? (en ? 'vacation' : 'vacacional') : (en ? 'for rent' : 'arriendo'));
    return '<a class="listing-card" href="listing.html?id=' + l.id + '">' +
      '<div class="listing-media"><img src="' + l.cover + '" alt="' + S.esc(S.title(l) + ', ' + l.city) + '" loading="lazy">' + badge + intl + '</div>' +
      '<div class="listing-body">' +
        '<div class="listing-price">' + D.fmtPrice(l) + ' <small>' + unit + '</small></div>' +
        '<div class="listing-title">' + S.esc(S.title(l)) + '</div>' +
        '<div class="listing-loc">' + S.esc(l.barrio + ' · ' + l.city) + '</div>' +
        '<div class="listing-specs">' + S.specs(l).map(function (s) { return '<span>' + s + '</span>'; }).join('') + '</div>' +
      '</div></a>';
  };
  S.esc = function (s) { return String(s == null ? '' : s).replace(/[&<>"]/g, function (c) { return ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;' })[c]; }); };
  S.initials = function (name) { return name.split(/\s+/).filter(Boolean).slice(0, 2).map(function (p) { return p[0]; }).join('').toUpperCase(); };

  /* -------------------------------------------------------- header / footer */
  S.renderChrome = function (opts) {
    opts = opts || {};
    var base = opts.home ? '' : 'index.html';
    var nav = [['inmuebles', base + '#inmuebles'], ['colecciones', base + '#colecciones'], ['lifestyle', 'lifestyle.html'], ['nosotros', base + '#nosotros'], ['contacto', base + '#contacto']];
    var header = document.getElementById('siteHeader');
    if (header) {
      header.className = 'container site-header dz-header';
      header.innerHTML =
        '<a class="site-logo" href="index.html"><span class="mark dz-mark">D</span> ' + S.esc(D.tenant.name) + '</a>' +
        '<nav class="site-nav" id="siteNav">' +
          nav.map(function (n) { return '<a href="' + n[1] + '" data-i18n="nav.' + n[0] + '"' + (opts.active === n[0] ? ' class="is-active"' : '') + '></a>'; }).join('') +
          (window.I18N ? window.I18N.toggleHtml() : '') +
          '<a class="btn btn-accent btn-sm" href="' + S.wa('Hola Dorum, quiero información sobre un inmueble.') + '" target="_blank" rel="noopener">' + S.icon('chat') + '<span data-i18n="nav.whatsapp"></span></a>' +
          '<button type="button" class="btn btn-ghost btn-icon dz-theme" id="themeBtn" data-i18n-label="nav.theme">' + S.icon('sun', 'dz-sun') + S.icon('moon', 'dz-moon') + '</button>' +
        '</nav>' +
        '<button type="button" class="btn btn-ghost btn-icon" id="navBtn" data-i18n-label="nav.menu">' + S.icon('menu') + '</button>';
      header.querySelector('#themeBtn').addEventListener('click', function () { D.setTheme(document.documentElement.dataset.theme === 'dark' ? 'light' : 'dark'); });
      header.querySelector('#navBtn').addEventListener('click', function () { document.getElementById('siteNav').classList.toggle('is-open'); });
    }
    var footer = document.getElementById('siteFooter');
    if (footer) {
      footer.className = 'site-footer dz-footer';
      footer.innerHTML =
        '<div class="container grid grid-4">' +
          '<div><a class="site-logo" href="index.html"><span class="mark dz-mark">D</span> ' + S.esc(D.tenant.name) + '</a>' +
            '<p class="small" style="margin-top:var(--s-3)" data-i18n="foot.tag"></p>' +
            '<p class="small muted" style="margin-top:var(--s-3)">' + S.esc(D.tenant.social.instagram) + ' · ' + S.esc(D.tenant.social.instagramLifestyle) + '</p></div>' +
          '<div><h4 data-i18n="foot.props"></h4><a href="' + base + '#inmuebles" data-mode="buy" data-i18n="foot.buy"></a><a href="' + base + '#inmuebles" data-mode="rent" data-i18n="foot.rent"></a><a href="' + base + '#inmuebles" data-mode="stay" data-i18n="foot.stay"></a><a href="' + base + '#colecciones" data-i18n="nav.colecciones"></a></div>' +
          '<div><h4 data-i18n="foot.group"></h4>' + D.tenant.divisions.map(function (dv) { return '<a href="' + (dv.id === 'lifestyle' || dv.id === 'projects' ? 'lifestyle.html' : base + '#divisiones') + '">' + S.esc(dv.name) + '</a>'; }).join('') + '</div>' +
          '<div><h4 data-i18n="nav.contacto"></h4><a href="' + base + '#nosotros" data-i18n="foot.about"></a><a href="' + base + '#contacto" data-i18n="foot.contact"></a><a href="' + S.WA + '" target="_blank" rel="noopener">WhatsApp · ' + S.esc(D.tenant.social.whatsappLabel) + '</a>' +
            '<span class="xs" style="display:block;margin-top:var(--s-3)" data-i18n="foot.legal"></span><span class="xs" style="display:block;margin-top:var(--s-1)">© 2026 ' + S.esc(D.tenant.legalName) + '</span></div>' +
        '</div>';
    }
    // "generated with Llave" ribbon
    if (!document.querySelector('.dz-ribbon')) {
      var r = document.createElement('a');
      r.className = 'dz-ribbon'; r.href = '../app/index.html#/role/owner/website';
      r.innerHTML = '<span class="dz-ribbon-mark">L</span><span data-i18n="foot.llave"></span><span class="dz-ribbon-sep">·</span><span data-i18n="foot.cms"></span>';
      document.body.appendChild(r);
    }
    S.applyLang();
  };

  /* --------------------------------------------------------------- lightbox */
  S.lightbox = function (images, start) {
    var i = start || 0;
    var lb = document.createElement('div');
    lb.className = 'dz-lightbox'; lb.setAttribute('role', 'dialog'); lb.setAttribute('aria-modal', 'true'); lb.setAttribute('aria-label', 'Galería');
    lb.innerHTML = '<button type="button" class="btn btn-ghost btn-icon dz-lb-close" aria-label="Cerrar">' + S.icon('x') + '</button>' +
      '<button type="button" class="btn btn-ghost btn-icon dz-lb-prev" aria-label="Anterior">' + S.icon('left') + '</button>' +
      '<figure><img alt=""><figcaption></figcaption></figure>' +
      '<button type="button" class="btn btn-ghost btn-icon dz-lb-next" aria-label="Siguiente">' + S.icon('right') + '</button>';
    var img = lb.querySelector('img'), cap = lb.querySelector('figcaption');
    function show(n) { i = (n + images.length) % images.length; img.src = images[i].url; img.alt = images[i].aiTags || ''; cap.textContent = (i + 1) + ' / ' + images.length + (images[i].aiTags ? ' · ' + images[i].aiTags : ''); }
    function close() { lb.remove(); document.removeEventListener('keydown', onKey); document.body.style.overflow = ''; }
    function onKey(e) { if (e.key === 'Escape') close(); if (e.key === 'ArrowRight') show(i + 1); if (e.key === 'ArrowLeft') show(i - 1); }
    lb.querySelector('.dz-lb-close').onclick = close;
    lb.querySelector('.dz-lb-prev').onclick = function () { show(i - 1); };
    lb.querySelector('.dz-lb-next').onclick = function () { show(i + 1); };
    lb.addEventListener('click', function (e) { if (e.target === lb) close(); });
    document.addEventListener('keydown', onKey);
    document.body.style.overflow = 'hidden';
    document.body.appendChild(lb); show(i);
    lb.querySelector('.dz-lb-close').focus();
  };

  /* --------------------------------------------------------- image fallback */
  // Picsum may be unreachable (offline demo): keep a soft ground instead of a broken icon.
  document.addEventListener('error', function (e) {
    var t = e.target; if (t && t.tagName === 'IMG') { t.classList.add('is-missing'); }
  }, true);
  function sweepImages() { document.querySelectorAll('img').forEach(function (im) { if (im.complete && im.naturalWidth === 0 && im.getAttribute('src')) im.classList.add('is-missing'); }); }
  window.addEventListener('load', sweepImages); setTimeout(sweepImages, 2500);

  window.SITE = S;
})();
